package com.zp.app.model;

import jakarta.persistence.*;
import lombok.Data;

@Entity
@Table(name = "global_control")
@Data
public class GlobalControl {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Integer id;

    @Column(unique = true, nullable = false)
    private String page;

    @Column(name = "is_button_disabled", nullable = false)
    private Boolean isButtonDisabled = false;

    @Column(name = "is_input_disabled", nullable = false)
    private Boolean isInputDisabled = false;

    @Column(name = "is_table_visible", nullable = false)
    private Boolean isTableVisible = true;

    // Getters and Setters are generated by Lombok @Data
}